### ISSUE TITLE
ToolFactory - dodac wiecej narzedzi

### ISSUE THREAD

**Issue by ms012** [ms012/imagefx#2]
Kubelek
Tekst
Zoomowanie
Przesuwanie
Opcje narzedzi

**Comment by ms012** [comment]
Potrzeba jeszcze drugiego spreju 😃

**Comment by MBudrowski** [comment]
Kubełek zrobiony w https://github.com/ms012/imagefx/commit/e283327b1935bb5f82330c5b8780c0e2d02a63ce

**Comment by MBudrowski** [comment]
Wszystkie narzędzia zrobione i działają. Narzędzie tekstu wymaga małej naprawy.
