### ISSUE TITLE
ToolDecorator - nowy dekorator grubosc linii, typ linii

### ISSUE THREAD

**Issue by ms012** [ms012/imagefx#3]

**Comment by MBudrowski** [comment]
Dekorator grubości linii zrobiony w https://github.com/ms012/imagefx/commit/e283327b1935bb5f82330c5b8780c0e2d02a63ce

**Comment by MBudrowski** [comment]
Dekorator stylu linii i czcionki zrobiony w https://github.com/ms012/imagefx/commit/062d81a1882fabba88a1db54c6a74c0c6c143f02
